---
title: "ProjectNHL"
author: "Deepak Karawande"
date: "June 13, 2021"
output:
  github_document:
    toc: yes
  html_document:
    toc: yes
    toc_float: no
---

```{r setup, include=FALSE}
require("httr")
require("jsonlite")
require("tidyverse")
```

## R Markdown


```{r}
get_baseURL <- function() { return("https://records.nhl.com/site/api") }

fetch_DF <- function(api_url) {
  get_response <- GET(api_url)
  json_contents <- content(get_response, "text")
  list_res <- fromJSON(json_contents, flatten = TRUE)
  return(list_res)
}

# get All Franchise

get_all_franchise <- function() {
  tab_name <- "franchise"
  full_url <- paste0(get_baseURL(), "/", tab_name)
  franchise_res <- fetch_DF(full_url)
  #str(list_res$data)
  franchise_res$data
}
get_all_franchise()

# Function returns id for team with common name matching to the argument provided. If tem name not found it will return NA.
get_franchise_id <- function(fname) {
  retValue <- NA
  
  franchise <- get_all_franchise() %>% filter(teamCommonName == fname)
  if(nrow(franchise) == 1) {
    retValue <- franchise$id
  }
  return(retValue)
}

get_franchise_id('Eagles')


#get Franchise by id, name or all franchise if no name or id is provided.
get_franchise <- function(franId=NA, franName="") {
  
  tab_name <- "franchise"
  full_url <- ""
  
  if(!is.na(franId)) {
    #get franchise by id
    id_filter <- paste0("cayenneExp=id=",franId)
    full_url <- paste0(get_baseURL(), "/", tab_name, "?", id_filter)
    
  } else if (!is.na(franName)) {
    #get franchise by name
    return(get_franchise(franId = get_franchise_id(franName)))
    
  } else {
    #both id and name are NA, let's return all franchises
    full_url <- paste0(get_baseURL(), "/", tab_name)
  
  }
  
  #fetch franchise
  franchise_res <- fetch_DF(full_url)
  return(franchise_res$data)
}

get_franchise(franId = 3)

get_franchise(franName = "Eagles")
```

## Including Plots

You can also embed plots, for example:

```{r}
get_total_stats <- function(franId) {
  tab_name <- "franchise-team-totals"
  id_filter <- paste0("cayenneExp=franchiseId=",franId)
  full_url <- paste0(get_baseURL(), "/", tab_name, "?", id_filter)
  list_total_stats <- fetch_DF(full_url)
  list_total_stats$data
}
get_total_stats(franId=17)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
```{r}
get_season_records <- function(franId) {
  tab_name <- "franchise-season-records"
  id_filter <- paste0("cayenneExp=franchiseId=",franId)
  full_url <- paste0(get_baseURL(), "/", tab_name, "?", id_filter)
  list_total_stats <- fetch_DF(full_url)
  list_total_stats$data
}
get_season_records(franId=17)
```

```{r}
get_goalie_records <- function(franId) {
  tab_name <- "franchise-goalie-records"
  id_filter <- paste0("cayenneExp=franchiseId=",franId)
  full_url <- paste0(get_baseURL(), "/", tab_name, "?", id_filter)
  list_total_stats <- fetch_DF(full_url)
  list_total_stats$data
}
get_goalie_records(franId=17)
```

```{r}
get_skater_records <- function(franId) {
  tab_name <- "franchise-skater-records"
  id_filter <- paste0("cayenneExp=franchiseId=",franId)
  full_url <- paste0(get_baseURL(), "/", tab_name, "?", id_filter)
  list_total_stats <- fetch_DF(full_url)
  list_total_stats$data
}
get_skater_records(franId=17)
```

```{r}
get_franchise_detail <- function(teamId) {
  tab_name <- "franchise-detail"
  id_filter <- paste0("cayenneExp=mostRecentTeamId=",teamId)
  full_url <- paste0(get_baseURL(), "/", tab_name, "?", id_filter)
  list_total_stats <- fetch_DF(full_url)
  list_total_stats$data
}
get_franchise_detail(teamId=17)
```

```{r}
#https://statsapi.web.nhl.com/api/v1/teams?expand=team.stats
#https://statsapi.web.nhl.com/api/v1/teams/17?expand=team.stats

get_team_stats_for_season <- function(teamId="") {
  full_url <- paste0("https://statsapi.web.nhl.com/api/v1/teams/",teamId,"?expand=team.stats")
  list_total_stats <- fetch_DF(full_url)
  list_total_stats$teams
}
a <- get_team_stats_for_season()
get_team_stats_for_season(teamId=17)

```

```{r}

NHL_wrapper_api <- function(command) {
  result = switch(  
      command,  
      "get_franchise"= get_franchise(),  
      "get_total_stats"= get_total_stats(17),  
      "get_season_records"= get_season_records(17),  
      "get_goalie_records"= get_goalie_records(17),
      "get_skater_records"= get_skater_records(17),
      "get_franchise_detail"= get_franchise_detail(teamId=17),
      "get_team_stats_for_season"= get_team_stats_for_season(teamId=17),
      "command not found"
  )
  return(result)
}

NHL_wrapper_api(command="get_team_stats_for_season")
```

```{r}

```

```{r}

```